### ISSUE TITLE
npm task cson2json not working

### ISSUE THREAD

**Issue by JCCR** [readium/readium-js-viewer#369]
I'm getting this error:
```
$ npm run cson2json

> readium-js-viewer@0.20.0-alpha cson2json /Users/juanc/Projects/readium
> node ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/concat.js package/*.cson package.cson && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/cson/bin/cson2json package.cson > package.json && node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js package.cson && node readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/optimizePackageJsonScripts.js

=== concat [package/package_base.cson] into [package/package_scripts_base.cson] ...
Input encoding: package/package_scripts_build.cson
-- append: package/package_base.cson
fs.js:105
    throw new Error('Unknown encoding: ' + encoding);
          ^
Error: Unknown encoding: package/package_scripts_build.cson
    at assertEncoding (fs.js:105:11)
    at Object.fs.readFileSync (fs.js:351:3)
    at /Users/juanc/Projects/readium/readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/concat.js:16:18
    at Array.forEach (native)
    at Object.<anonymous> (/Users/juanc/Projects/readium/readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/concat.js:14:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

I found that the way to fix this is to wrap the `package/*.cson` portion of the command `concat.js package/*.cson package.cson` in double quotes:

```coffeescript
scripts:

#=====================
    cson2json: '
        node ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/concat.js "package/*.cson" package.cson
        &&
        node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/cson/bin/cson2json package.cson > package.json
        &&
        node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js package.cson
        &&
        node readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/optimizePackageJsonScripts.js
    '
```

Why? because it seems that my environment (OSX, bash?, the args parser?) that executes this command is recognizing the glob pattern and it is transforming the command into 
```
node ./readium-js/readium-shared-js/readium-cfi-js/readium-build-tools/concat.js 'package/package_base.cson' 'package/package_scripts_base.cson' 'package/package_scripts_build.cson' 'package/package_scripts_dist_base.cson' 'package/package_scripts_dist_chromeApp.cson' 'package/package_scripts_dist_cloudReader.cson' 'package/package_scripts_dist_cloudReaderLite.cson' 'package/package_scripts_http.cson' 'package/package_scripts_test_base.cson' 'package/package_scripts_test_sauce.cson' 'package/package_scripts_travis.cson' 'package.cson' package.cson
```

cc @danielweck

**Comment by danielweck** [comment]
Thanks Juan! Fixed via https://github.com/readium/readium-js-viewer/commit/13dc0697fdeb7853a416cb02cceedc77fc5ff4dc
