### ISSUE TITLE
GitHub "release" API fails on Travis!

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#529]
https://travis-ci.org/readium/readium-js-viewer/jobs/136713346#L3295
```
$ [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ${MODE} = "chromeApp" ] && node build-config/deployCrx.js
deploying crx to github
0.24.0-alpha tag does not exist, creating.
/home/travis/build/readium/readium-js-viewer/build-config/deployCrx.js:48
    github.releases.listReleases({owner: owner, repo: repo}, function(error, releases){
                   ^
TypeError: Cannot read property 'listReleases' of undefined
    at deleteOldRelease (/home/travis/build/readium/readium-js-viewer/build-config/deployCrx.js:48:20)
    at /home/travis/build/readium/readium-js-viewer/node_modules/github/lib/index.js:786:17
    at callCallback (/home/travis/build/readium/readium-js-viewer/node_modules/github/lib/index.js:639:17)
    at IncomingMessage.<anonymous> (/home/travis/build/readium/readium-js-viewer/node_modules/github/lib/index.js:698:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by danielweck** [comment]
The tag was created, but not the release body:
https://github.com/readium/readium-js-viewer/releases/tag/0.24.0-alpha

**Comment by danielweck** [comment]
...which should look like:
https://github.com/readium/readium-js-viewer/releases/tag/0.23.0-alpha

**Comment by danielweck** [comment]
https://travis-ci.org/readium/readium-js-viewer/jobs/136727906#L3293
```
$ [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ${MODE} = "chromeApp" ] && node build-config/deployCrx.js
deploying crx to github
updating previous "0.24.0-alpha" release tag
/home/travis/build/readium/readium-js-viewer/build-config/deployCrx.js:48
    github.releases.listReleases({owner: owner, repo: repo}, function(error, releases){
                   ^
TypeError: Cannot read property 'listReleases' of undefined
    at deleteOldRelease (/home/travis/build/readium/readium-js-viewer/build-config/deployCrx.js:48:20)
    at /home/travis/build/readium/readium-js-viewer/node_modules/github/lib/index.js:786:17
    at callCallback (/home/travis/build/readium/readium-js-viewer/node_modules/github/lib/index.js:639:17)
    at IncomingMessage.<anonymous> (/home/travis/build/readium/readium-js-viewer/node_modules/github/lib/index.js:698:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by danielweck** [comment]
GitHub NodeJS util API breaking change?
https://mikedeboer.github.io/node-github/#api-repos-getReleases

**Comment by danielweck** [comment]
Fixed by https://github.com/readium/readium-js-viewer/commit/6636282521645ba992ab5b2710fb34c328c2ae0a

Proof:
https://travis-ci.org/readium/readium-js-viewer/jobs/136741603#L3295
```
$ [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ${MODE} = "chromeApp" ] && node build-config/deployCrx.js
deploying crx to github
updating previous "0.24.0-alpha" release tag
BUILD DATE/TIME: Fri, 10 Jun 2016 16:20:51 GMT
BUILD tag: 0.24.0-alpha
TRAVIS_BRANCH: develop
TRAVIS_COMMIT: 6636282521645ba992ab5b2710fb34c328c2ae0a
TRAVIS_JOB_NUMBER: 624.1
TRAVIS_BUILD_ID: 136741602
TRAVIS_BUILD_NUMBER: 624
release created
UPLOAD TO RELEASE: [Readium.crx] from [/home/travis/build/readium/readium-js-viewer/dist/Readium.crx] (application/x-chrome-extension)
binary uploaded successfully
UPLOAD TO RELEASE: [Readium_cloud-reader.zip] from [/home/travis/build/readium/readium-js-viewer/dist/Readium_cloud-reader.zip] (application/zip)
binary uploaded successfully
UPLOAD TO RELEASE: [Readium_cloud-reader-lite.zip] from [/home/travis/build/readium/readium-js-viewer/dist/Readium_cloud-reader-lite.zip] (application/zip)
binary uploaded successfully
```

Result:
https://github.com/readium/readium-js-viewer/releases/tag/0.24.0-alpha
