### ISSUE TITLE
npm run prepare:submodule and npm run prepare:local failed on the system

### ISSUE THREAD

**Issue by anjietha09** [readium/readium-js-viewer#602]
[New Text Document.txt](https://github.com/readium/readium-js-viewer/files/746805/New.Text.Document.txt)
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prepare' ]
2 info using npm@4.1.2
3 info using node@v6.9.1
4 warn invalid config registry=""
5 warn invalid config Must be a full url with 'http://'
6 verbose run-script [ 'prepare' ]
7 info lifecycle readium-js@0.24.0~prepare: readium-js@0.24.0
8 verbose lifecycle readium-js@0.24.0~prepare: unsafe-perm in lifecycle true
9 verbose lifecycle readium-js@0.24.0~prepare: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\TONEW\readium-js-viewer\readium-js\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\TONEW\readium-js-viewer\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\TONEW\readium-js-viewer\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\nodejs\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Users\TONEW\AppData\Roaming\npm
10 verbose lifecycle readium-js@0.24.0~prepare: CWD: C:\Users\TONEW\readium-js-viewer\readium-js
11 silly lifecycle readium-js@0.24.0~prepare: Args: [ '/d /s /c',
11 silly lifecycle   'npm run prepare:submodule && npm run prepare:local' ]
12 silly lifecycle readium-js@0.24.0~prepare: Returned: code: 1  signal: null
13 info lifecycle readium-js@0.24.0~prepare: Failed to exec prepare script
14 verbose stack Error: readium-js@0.24.0 prepare: `npm run prepare:submodule && npm run prepare:local`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid readium-js@0.24.0
16 verbose cwd C:\Users\TONEW\readium-js-viewer\readium-js
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepare"
19 error node v6.9.1
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error readium-js@0.24.0 prepare: `npm run prepare:submodule && npm run prepare:local`
22 error Exit status 1
23 error Failed at the readium-js@0.24.0 prepare script 'npm run prepare:submodule && npm run prepare:local'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the readium-js package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run prepare:submodule && npm run prepare:local
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs readium-js
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls readium-js
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by danielweck** [comment]
couple of things:
please try with the develop branch (in all repositories and submodules)
please uninstall nodejs v6.9.1 and install v6.9.5 from:
https://nodejs.org

**Comment by anjietha09** [comment]
getting same after performing the changes

**Comment by anjietha09** [comment]
same error*

**Comment by danielweck** [comment]
You should have NPM v `3.10.10` (which ships with Node `6.9.5`), yet your console log is showing `4.1.2`. I think that is the problem.

**Comment by JCCR** [comment]
Try downgrading to NPM v3:

npm install -g npm@latest-3

I'm going to close this since I think this is the same problem as in #600.
