### ISSUE TITLE
NPM Errors

### ISSUE THREAD

**Issue by sage-IT** [readium/readium-js-viewer#617]
Hi,

I am having issues installing the new Readium Distribution. I get issues running the NPM package manager. See below. I am trying this on a linux BSD Ubuntu 14.04.5 LTS, with NPM version 2.15.11 and nodeJS version -v4.8.0

#### Related issue(s) and/or pull request(s)
issues/509

Moved to directory readium-js
Run Command `sudo npm run prepare`
Expected Readium to install and update the latest packages, fails with NPM errors from npm-debug.log in root folder.
 `0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'clean' ]`
`2 info using npm@2.15.11`
`3 info using node@v4.8.0`
`4 verbose run-script [ 'preclean', 'clean', 'postclean' ]`
`5 info preclean readium-js-viewer@0.25.0`
`6 info clean readium-js-viewer@0.25.0`
`7 verbose unsafe-perm in lifecycle true`
`8 info readium-js-viewer@0.25.0 Failed to exec clean script`
`9 verbose stack Error: readium-js-viewer@0.25.0 clean: `node --version && npm --version && node` `./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js build-output && node` `./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js api-docs/* && node` `./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js dist`
`9 verbose stack Exit status 1`
`9 verbose stack     at EventEmitter.<anonymous>` `(/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)`
`9 verbose stack     at emitTwo (events.js:87:13)`
`9 verbose stack     at EventEmitter.emit (events.js:172:7)`
`9 verbose stack     at ChildProcess.<anonymous>`(/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)`
`9 verbose stack     at emitTwo (events.js:87:13)`
`9 verbose stack     at ChildProcess.emit (events.js:172:7)`
`9 verbose stack     at maybeClose (internal/child_process.js:854:16)`
`9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)`
`10 verbose pkgid readium-js-viewer@0.25.0`
`11 verbose cwd /var/www/html/Readium2/readium-js-viewer/readium-js`
`12 error Linux 3.13.0-113-generic`
`13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "clean"`
`14 error node v4.8.0`
`15 error npm  v2.15.11`
`16 error code ELIFECYCLE`
`17 error readium-js-viewer@0.25.0 clean: `node --version && npm --version && node ./readium-`js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js build-output && node ./readium-`js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js api-docs/* && node ./readium-`js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js dist`
`17 error Exit status 1`
`18 error Failed at the readium-js-viewer@0.25.0 clean script 'node --version && npm --version && `node ./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js build-output && node `./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js api-docs/* && node `./readium-js/readium-shared-js/readium-cfi-js/node_modules/rimraf/bin.js dist'.`
`18 error This is most likely a problem with the readium-js-viewer package,`
`18 error not with npm itself.`
`18 error Tell the author that this fails on your system:`
`18 error     node --version && npm --version && node ./readium-js/readium-shared-js/readium-cfi-`js/node_modules/rimraf/bin.js build-output && node ./readium-js/readium-shared-js/readium-cfi-`js/node_modules/rimraf/bin.js api-docs/* && node ./readium-js/readium-shared-js/readium-cfi-`js/node_modules/rimraf/bin.js dist`
`18 error You can get information on how to open an issue for this project with:`
18 error     npm bugs readium-js-viewer`
`18 error Or if that isn't available, you can get their info via:`
`18 error`
`18 error     npm owner ls readium-js-viewer`
`18 error There is likely additional logging output above.`
`19 verbose exit [ 1, true ]`

Readium packages are not installed and prepared correctly

#### Steps to reproduce
1. Download the repository via git: `git clone https://github.com/readium/readium-js-viewer.git`
2. Then run the command 'npm run prepare'
3. I also tried to download the entire git repository again and do the install and update steps but still no lcuk

* Readium cloud reader app
 1. Cannot execute the command `npm run dist`

**Comment by sage-IT** [comment]
Hey I uninstalled nodejs and npm and reinstalled it with version 6 and 4 respectively and it all seems to be working now. This can be closed now
