### ISSUE TITLE
Git lib (gift), broken build system on TravisCI for Pull Requests (feature branches)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#716]
Code culprit:
https://github.com/readium/readium-shared-js/blob/develop/readium-build-tools/versionsMaker.js#L32

Outcome:
https://travis-ci.org/readium/readium-js-viewer/pull_requests

```
/home/travis/build/readium/readium-js-viewer/node_modules/gift/lib/commit.js:176
      ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], epoch = ref1[2];
                                                       ^
TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (/home/travis/build/readium/readium-js-viewer/node_modules/gift/lib/commit.js:176:56)
    at Function.module.exports.Commit.parse_commits (/home/travis/build/readium/readium-js-viewer/node_modules/gift/lib/commit.js:139:21)
    at /home/travis/build/readium/readium-js-viewer/node_modules/gift/lib/commit.js:99:39
    at ChildProcess.exithandler (child_process.js:265:7)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! readium-js-viewer@0.31.0-alpha versioning: "node build-config/versioning.js build-output/version.json"
```

**Comment by danielweck** [comment]
Suggestion: may be due to "detached head" state of local Git cloned repository (on TravisCI).

`git status` =>
```
HEAD detached at FETCH_HEAD
```

Compare with working builds from the develop branch:

`git status` =>
```
On branch develop
Your branch is up to date with 'origin/develop'.
```
